# Generated by Django 3.2.5 on 2021-07-26 03:02

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(default='', max_length=20, unique=True)),
                ('password', models.CharField(default='', max_length=25, unique=True)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('points', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
            managers=[
                ('users', django.db.models.manager.Manager()),
            ],
        ),
    ]
